development:
  adapter: postgresql
  encoding: unicode
  database: fitness_app
  pool: 5
  username:
  password:

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: myapp_test
#   pool: 5
#   username: myapp
#   password: password1